### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectC_Group10#148] opened 2016-03-17 16:13 UTC
As discussed today after the fantastic demo, we need a public website where I can show this off to some ppl. I running it off the repo but then realized I am missing some deps and then ran out of time trying to set shit up. THEN i realized it's not my job. So please help me help you and set a public end point for this absolutely cool app that you developed.

**Comment by AlexBeischl** [comment] 2016-03-17 16:57
Hi @gyachdav  ,
@mbandle is our js. and web-dev. expert and our project manager, @AlexMoroz from project E is our npm magician.
I've informed both of them as they have more knowledge how to do that :smile:

**Comment by sacdallago** [comment] 2016-03-17 17:52
This is a duplicate of #141 Please let's continue this discussion there.
The faster you do this, the better it is guys! We have an AWESOME domain name now (that's gonna be my surprise for you tomorrow, no screenshots :D)

**Comment by AlexMoroz** [comment] 2016-03-17 18:07
I can't see how the Demo site, can be duplication of Documentation Documentation Documentation :)

**Comment by sacdallago** [comment] 2016-03-17 19:09
Well, C10 already provides a _site_, so the only thing that @gyachdav was lacking were comprehensive instructions on how to run the whole thing :dancer:

**Comment by tPiffrader** [comment] 2016-03-17 19:10
I am on it :smile:

**Comment by gyachdav** [comment] 2016-03-17 20:58
wait, what?? so @mbandle is assignee here or @tPiffrader?

@sacdallago no,I don't need instructions how to install it. I just need C10 to provide a public endpoint I can send to people. I won't have time to install this on my rostlab pub folder anyways.

**Comment by sacdallago** [comment] 2016-03-17 21:27
@gyachdav so you want them to host this somewhere? Because if that I set up a thing on our server now/2morrow

**Comment by tPiffrader** [comment] 2016-03-17 21:31
@gyachdav I am the one for the readme and documentation. @mbandle is doing refactoring at the moment :+1:

**Comment by gyachdav** [comment] 2016-03-17 21:41
yup I want them to host it somewhere. thanks!

**Comment by sacdallago** [comment] 2016-03-17 22:17
Guys I need ~10 minutes of your time tomorrow <3

**Comment by sacdallago** [comment] 2016-03-17 22:18
Possibly before the presentations start (9:30)! Come to rostlab please (01.09.053? It's like at the end of the corridor on the right!)

**Comment by AlexBeischl** [comment] 2016-03-17 23:35
Ok, we will be there :smile:

**Comment by bandle** [comment] 2016-03-18 08:35
@sacdallago 
We are there. Where are you?

**Comment by sacdallago** [comment] 2016-03-18 09:46
http://map.got.show

**Closed as completed by sacdallago** 2016-03-18 09:46 UTC

**Comment by gyachdav** [comment] 2016-03-18 09:49
Beautiful!

**Comment by sacdallago** [comment] 2016-03-21 14:27
I just realized that I can simply switch to the `gh-pages` branch inside my clone of the repo and git pulling will already update the whole thing :D :D so now the github page version is also serviced on the http://map.got.show

**Comment by bandle** [comment] 2016-03-21 14:54
And so this map also is responsive :+1:
