### ISSUE TITLE
Some images are not accessible

### ISSUE THREAD

**Issue by AlexMoroz** [Rostlab/JS16_ProjectC_Group10#130] opened 2016-03-16 09:28 UTC
> https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/labels/0/y0x-1.png 404 (Not Found) y0x2.png:1 GET https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/bg/0/y0x2.png 404 (Not Found) y0x1.png:1 GET https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/bg/0/y0x1.png 404 (Not Found) y0x-1.png:1 GET https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/bg/0/y0x-1.png 404 (Not Found) y0x2.png:1 GET https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/labels/0/y0x2.png 404 (Not Found) y0x1.png:1 GET https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/labels/0/y0x1.png 404 (Not Found)

https://github.com/Rostlab/JS16_ProjectF/issues/17#issuecomment-197188057

**Comment by bandle** [comment] 2016-03-16 09:30
These images actually don't exist. Its a bug in leaflet that it tries to load them.
They are out of map bounds.

**Comment by bandle** [comment] 2016-03-16 09:30
you made a duplicate of #129

**Closed as completed by bandle** 2016-03-16 09:30 UTC
